### PR TITLE
docs: tidy all READMEs

### PR DESCRIPTION
**Pull request by 413x1nkp**
using HTML in markdown is not a good practice in general, however some things that exist in HTML do not yet exist in markdown, such as centering a sector of text; therefore `<div align="center"></div>` can not be removed without altering the looks of the README.

reading through all of the README files made me realize how most of them are outdated... gonna work on that at some point though

### CODE REVIEW

**Comment by 413x1nkp** [comment]
...huh?
```
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 e0d9e200afe57c69c6407c90189c7f16a55ce326d1ac45864353e13bfe574b3c
             Got        5e4458986055bafa450b3d803f4653bdf760c42107c78710f76e7e0174b9dfc2
```
i only changed README files lul, ig some pip modules were updated recently?

**Comment by fumiama** [comment]
Maybe just an internal error.

**Review by fumiama — APPROVED** [review]

**Comment by fumiama** [comment]
Perhaps you have noticed that the screen shot in the table is broken. I will repair it later.

**Comment by 413x1nkp** [comment]
> Perhaps you have noticed that the screen shot in the table is broken. I will repair it later.

Just created an issue :sweat_smile: 
I guess I'll left it open for now

**Comment by fumiama** [comment]
OK.

**Pull request merged**
