### PR TITLE
refactor(structure): merge `infer` dir into `rvc` for move uniform API access

### PR DESCRIPTION
**Pull request by 413x1nkp**
this also moves `train` from `infer.lib` to `rvc.lib` which just makes more sense than having `train` under `infer`

might be too extreme of a change for now, but hopefully not, since this tidies up the structure quite drastically

### CODE REVIEW

**Comment by 413x1nkp** [comment]
i guess i could preserve the split of `train` and `infer` by making dirs that contain scripts that either one needs, not sure if this would be necessary though... but i'm up to making changes!

**Comment by fumiama** [comment]
Well, don't be so hurry 😂. I'm moving the infer to rvc gradually, by viewing the codes line by line and place them into the proper position to modularize it. Now, just keep the half-infer half-rvc status and the infer part will decrease, the rvc part will increase.

**Comment by 413x1nkp** [comment]
Yeah, sorry, I'm quite hasty when it comes to making some changes which I planned to do for months :sweat_smile: 
I thought it'd be easier to first move things in their new places and then start making changes about how these things are used, but I guess that is not always the case...
Should i close this PR?

**Comment by fumiama** [comment]
> I thought it'd be easier to first move things in their new places and then start making changes about how these things are used

Move many stuffs at the same time will make it easier to ignore some codes refer to it.

> Should i close this PR?

Yes, you should. But thanks to your passion. If you like, you can separate the `uvr5_park` part first, which will not be included in the rvc folder.

**Comment by 413x1nkp** [comment]
Alrighty then :)

**Pull request closed without merging**
