### PR TITLE
README cleanup + docs removal

### PR DESCRIPTION
**Pull request by blaisewf**
I have rewritten some parts of the readme to make it more user-friendly.

I suggest that once you finish editing everything, then you can make the translations to all the languages you want and redo the docs in all the languages (the current docs were highly outdated).

### CODE REVIEW

**Comment by 413x1nkp** [comment]
some of your changes revert commit in the tip...

**Comment by fumiama** [comment]
Yes. You can see the `Files changed` section.

**Comment by fumiama** [comment]
And maybe not be so radical. The README can leave and we just modify it.

**Comment by fumiama** [comment]
Outdate is better than none, though.

**Comment by 413x1nkp** [comment]
Yeah, removing all of the localization seems a bit excessive. I understand the idea behind the PR, but removing the translated READMEs and docs is not the best solution...

However, the changelogs can go IMO. changelogs are useless since we have a thing called `git tags` and `Releases`, those can and SHOULD contain the changelogs

Also, the changelogs should be on per-tag basis, not the per-day or per-month since it's much harder to find the commit that was made on a specific date, but with tags it's as easy as `git checkout tags/<TAG> -b <branch>`; so i guess we should start working on the tags and releases now, huh?

i'm honestly not sure if one can make a PR for adding tags or releases though, so i have no idea on how to actually go about doing that for the repo.

**Comment by fumiama** [comment]
> However, the changelogs can go IMO.

I agree.

> i'm honestly not sure if one can make a PR for adding tags or releases though

I don't want to copy the change logs and make many releases. Let start a release from zero. Of course, the version tag should be v2.x.x.

**Comment by 413x1nkp** [comment]
> I don't want to copy the change logs and make many releases. Let start a release from zero. Of course, the version tag should be v2.x.x.

Sounds like a plan!

**Pull request closed without merging**
