### PR TITLE
chore(structure): rename requirements files

### PR DESCRIPTION
**Pull request by 413x1nkp**
all of the requirements under `requirements/` have requirements-* in their name, which just looks dirty since all of the requirements are already in the `requirements` dir. therefore to have cleaner project, it's better to rename all the req files to just contain info on what each of them does

i attempted to change the reqfiles names everywhere where they are used, but if i missed some places where old names are still in use - please let me know.

### CODE REVIEW

**Review by fumiama — DISMISSED** [review]

**Comment by fumiama** [comment]
Well, this change breaks the unit test. You can search the string `requirements` in the whole repo and replace every places.

**Comment by 413x1nkp** [comment]
Apologies! Forgot to change requirements path in unitest workflow. Now all checks pass

**Review by fumiama — APPROVED** [review]
Well, not a big problem. Thanks for your contributing.

**Comment by 413x1nkp** [comment]
I think this should be re-merged... I forgot to change the requirements files mentioned in the README... Sorry :sweat_smile: 
Updated my dev branch to include this change

**Comment by fumiama** [comment]
Well, just create a new PR.

**Pull request merged**
